### PR TITLE
Add ChangeLog for 1.0 release

### PR DESCRIPTION
**Pull request by szyrom**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @szyrom)

___
*[ChangeLog, line 6 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40#-LqG2Lon7efA8hCmWaym:-LqG2LooA50j4aLt1yqN:b-o4b7cw) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/29d946ff97865db8bb60517ea60ad232c7ae34e1/ChangeLog#L6)):*
> ```
> 
> 	This is the first release of pmemkv-nodejs project which guarantees
>         backward compatibility.
> ```

strange indentation

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40)* status: all files reviewed, 3 unresolved discussions (waiting on @szyrom)

___
*[ChangeLog, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40#-LqL5CM80cbiPGV5od6m:-LqL5CM80cbiPGV5od6n:b32v9l) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/29d946ff97865db8bb60517ea60ad232c7ae34e1/ChangeLog#L1)):*
> ```
> Thu Oct 03 2019 Szymon Romik <szymon.romik@intel.com>
> ```

04
___
*[ChangeLog, line 8 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40#-LqL5Mrb3j45gNyscsdy:-LqL5Mrb3j45gNyscsdz:bpe8zmd) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/29d946ff97865db8bb60517ea60ad232c7ae34e1/ChangeLog#L8)):*
> ```
>         backward compatibility.
> 
>         It provides Node.js bindings to libpmemkv 1.0. The API is functionnally
> ```

functionally

**Review by szyrom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[ChangeLog, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40#-LqL5CM80cbiPGV5od6m:-LqLdH978yUpMlUydCTi:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/29d946ff97865db8bb60517ea60ad232c7ae34e1/ChangeLog#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

04
</blockquote></details>

Done.
___
*[ChangeLog, line 6 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40#-LqG2Lon7efA8hCmWaym:-LqLdHMmAvw4rHSvNrGJ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/29d946ff97865db8bb60517ea60ad232c7ae34e1/ChangeLog#L6)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

strange indentation
</blockquote></details>

Done.
___
*[ChangeLog, line 8 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40#-LqL5Mrb3j45gNyscsdy:-LqLdHf66Cx-PAzQf8UH:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/29d946ff97865db8bb60517ea60ad232c7ae34e1/ChangeLog#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

functionally
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/40)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Pull request closed without merging**
