### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by annamarcink**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
let's adjust this PR with the latest version of PR from pmem/pmemkv-ruby#28 (probably at best, after ruby one is merged)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26)* status: all files reviewed, 3 unresolved discussions (waiting on @annamarcink)

___
*[utils/docker/run-build.sh, line 43 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26#-LnNkKUVCSD9MEjXHubg:-LnNkKUVCSD9MEjXHubh:bjqxyzh) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/2aade23e9935f812d3fdb67f108dfd83451d4f6b/utils/docker/run-build.sh#L43)):*
> ```Shell
> 
> # build and install pmemkv
> cd ~
> ```

not necessary
___
*[utils/docker/run-build.sh, line 55 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26#-LnNkR8M5V-F3wItvz1h:-LnNkR8M5V-F3wItvz1i:b-303026) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/2aade23e9935f812d3fdb67f108dfd83451d4f6b/utils/docker/run-build.sh#L55)):*
> ```Shell
> echo
> echo "##################################################################"
> echo "### Verifying building and installing of the pmemkv-nodejs binding"
> ```

you could actually re-phrase it.
1. it obvious it's for nodejs bindings,
2. we verify building, installation and we execute tests
___
*[utils/docker/run-build.sh, line 58 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26#-LnNd27HAhKykBWfBKOF:-LnNd27I8fqpkoy14z4A:br1hadd) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/2aade23e9935f812d3fdb67f108dfd83451d4f6b/utils/docker/run-build.sh#L58)):*
> ```Shell
> echo "##################################################################"
> cd $WORKDIR
> npm install --save
> ```

'npm install` should be enough I believe

**Review by annamarcink — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 43 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26#-LnNkKUVCSD9MEjXHubg:-LnROP8m44BI7p8QXhbK:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/2aade23e9935f812d3fdb67f108dfd83451d4f6b/utils/docker/run-build.sh#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not necessary
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 55 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26#-LnNkR8M5V-F3wItvz1h:-LnROR0d6eWeAemNTIVG:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/2aade23e9935f812d3fdb67f108dfd83451d4f6b/utils/docker/run-build.sh#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could actually re-phrase it.
1. it obvious it's for nodejs bindings,
2. we verify building, installation and we execute tests
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 58 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26#-LnNd27HAhKykBWfBKOF:-LnROS99AXmSfa7dN0U_:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/2aade23e9935f812d3fdb67f108dfd83451d4f6b/utils/docker/run-build.sh#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

'npm install` should be enough I believe
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26)* status: all files reviewed, 4 unresolved discussions (waiting on @annamarcink and @lukaszstolarczuk)

___
*[utils/docker/images/build-image.sh, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26#-LnRwuIv4mmeTp6jrEPf:-LnRwuIv4mmeTp6jrEPg:b-7fpuf1) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/fe91aebff574072b67d8882c199c99362123c918/utils/docker/images/build-image.sh#L35)):*
> ```Shell
> #
> # build-image.sh <OS-VER> - prepares a Docker image with <OS>-based
> #                           environment for testing pmemkv-ruby, according
> ```

pmemkv-nodejs

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26)* status: all files reviewed, 1 unresolved discussion (waiting on @annamarcink)

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/26#-:-LnWgO4v3pfWXBb9sfJw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @annamarcink)

**Pull request merged**
