### PR TITLE
Update installation tips

### PR DESCRIPTION
**Pull request by annamarcink**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/20)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/20)* status: all files reviewed, 2 unresolved discussions (waiting on @annamarcink)

___
*[README.md, line 31 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/20#-LhGD_no2PV2jsf-4OBb:-LhGD_no2PV2jsf-4OBc:btb4srq) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/4432f3dc7bc7a82141f7df3fcaef7258ad4bde7c/README.md#L31)):*
> ```Markdown
> ```
> 
> Add npm module to your project:
> ```

this sentence seems a bit misleading... not sure what we wanted to achieve
I mean, based on https://docs.npmjs.com/cli/install command `npm install <folder>` vs `npm install (no args)` seems to have different results... and I'm not sure where do we want to install it (see also: https://docs.npmjs.com/files/folders)
___
*[README.md, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/20#-LhGFBqjDupp3pQ3TV1_:-LhGFBqjDupp3pQ3TV1a:b-1qhkgb) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/4432f3dc7bc7a82141f7df3fcaef7258ad4bde7c/README.md#L42)):*
> ```Markdown
> 
> ```
> LD_LIBRARY_PATH=path_to_your_libs npm test
> ```

do we need to be in pmemkv-nodejs dir here too?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/20)* status: all files reviewed, 1 unresolved discussion (waiting on @annamarcink)

___
*[README.md, line 42 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/20#-LhGFBqjDupp3pQ3TV1_:-LhGPkxKDNkBlKWLQUEL:b-b2hy8z) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/4432f3dc7bc7a82141f7df3fcaef7258ad4bde7c/README.md#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we need to be in pmemkv-nodejs dir here too?
</blockquote></details>

I'm retracting this, since we never (in none of the other bindings) specify that (it's kind of obvious I guess)

**Review by annamarcink — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/20)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[README.md, line 31 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/20#-LhGD_no2PV2jsf-4OBb:-LiIQqFI-pOmQncVfvz3:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/4432f3dc7bc7a82141f7df3fcaef7258ad4bde7c/README.md#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this sentence seems a bit misleading... not sure what we wanted to achieve
I mean, based on https://docs.npmjs.com/cli/install command `npm install <folder>` vs `npm install (no args)` seems to have different results... and I'm not sure where do we want to install it (see also: https://docs.npmjs.com/files/folders)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/20#-:-LiIa9Kb4HfzMLsmXkG7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
