### PR TITLE
Adjust to all pmemkv API changes

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/21)

### CODE REVIEW

**Review by szyrom — COMMENTED** [review]
don't we want to have both get_all and get_all_keys (second one implemented with get_all from C)? 

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/21#-:-LiOfmUk-r2ZTld6yDZ7:brjvisy)* status: 0 of 8 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
Yes, we want, but Ania has it ready in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/21#-:-LiSCnlg4JZoPdWT5M2R:bwq9qd5)* status: 0 of 8 files reviewed, all discussions resolved

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/21)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[lib/database.cc, line 122 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/21#-LiSwE35DI0Ot44WOQS1:-LiSwE35DI0Ot44WOQS2:b-oduoq8) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/469a1f821cb54908556a60fe0952a8afcb64f850/lib/database.cc#L122)):*
> ```cpp
>     Napi::Function cb = info[1].As<Napi::Function>();
>     this->_db.get_below(key, [&](pmem::kv::string_view key, pmem::kv::string_view value) -> int {
>         cb.Call(env.Global(), {Napi::String::New(env, key.data()), Napi::String::New(env, value.data())});
> ```

actually get_keys should not pass value to Node.js (please remove Napi::String::New(env, value.data())). The same of other keys_* methods

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/21)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[lib/database.cc, line 122 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/21#-LiSwE35DI0Ot44WOQS1:-LiT7FKC1nWPR-lxhGtb:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/469a1f821cb54908556a60fe0952a8afcb64f850/lib/database.cc#L122)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

actually get_keys should not pass value to Node.js (please remove Napi::String::New(env, value.data())). The same of other keys_* methods
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/21#-:-LiTNdGX3k3savVqFxBz:bnfp4nl)* status: 0 of 9 files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> Reviewed 3 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/21#-:-LiTcxTV9ai-xeNjJNtT:bnfp4nl)* status: 2 of 9 files reviewed, all discussions resolved (waiting on @szyrom)

**Pull request merged**
