### PR TITLE
Update Travis files

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
i.a.:
- update Ubuntu to 19.10
- add Fedora image (v. 31)
- remove memkind installation script
- enable both stable and current pmemkv's build

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.fedora-31, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-LtilskPB1tv5bUXHQr1:-LtilskQDm_kII6YjPzm:b-ybw9lp) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/8490f3269aa28994761dfcec3966ef9176a7dc50/utils/docker/images/Dockerfile.fedora-31#L39)):*
> ```
> # Pull base image
> FROM fedora:31
> MAINTAINER lukasz.stolarczuk@intel.com
> ```

szymon.romik
___
*[utils/docker/images/Dockerfile.fedora-31, line 102 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-Ltilv653ZSP4JMjgrs4:-Ltilv653ZSP4JMjgrs5:byhyz6n) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/8490f3269aa28994761dfcec3966ef9176a7dc50/utils/docker/images/Dockerfile.fedora-31#L102)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> # Set required environment variables
> ENV OS fedora
> ENV OS_VER 31
> ENV PACKAGE_MANAGER rpm
> ENV NOTTY 1
> ```
</details>


please move it to the beginning
___
*[utils/docker/images/Dockerfile.ubuntu-19.10, line 99 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-LtilxmS1qhg8tVjUO8j:-LtilxmS1qhg8tVjUO8k:b-rmills) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/8490f3269aa28994761dfcec3966ef9176a7dc50/utils/docker/images/Dockerfile.ubuntu-19.10#L99)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> # Set required environment variables
> ENV OS ubuntu
> ENV OS_VER 19.10
> ENV PACKAGE_MANAGER deb
> ENV NOTTY 1
> ```
</details>


please move it to the beginning

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48)* status: 4 of 9 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.fedora-31, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-LtilskPB1tv5bUXHQr1:-Lu1q5h7A-9nLpdgcfvM:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/8490f3269aa28994761dfcec3966ef9176a7dc50/utils/docker/images/Dockerfile.fedora-31#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

szymon.romik
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-31, line 102 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-Ltilv653ZSP4JMjgrs4:-Lu1q60LE-m0RnH1onNx:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/8490f3269aa28994761dfcec3966ef9176a7dc50/utils/docker/images/Dockerfile.fedora-31#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # Set required environment variables
> ENV OS fedora
> ENV OS_VER 31
> ENV PACKAGE_MANAGER rpm
> ENV NOTTY 1
> ```

please move it to the beginning
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.ubuntu-19.10, line 99 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-LtilxmS1qhg8tVjUO8j:-Lu1q7_f8xonNXycZNvq:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/8490f3269aa28994761dfcec3966ef9176a7dc50/utils/docker/images/Dockerfile.ubuntu-19.10#L99)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # Set required environment variables
> ENV OS ubuntu
> ENV OS_VER 19.10
> ENV PACKAGE_MANAGER deb
> ENV NOTTY 1
> ```

please move it to the beginning
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/install-libpmemobj-cpp.sh, line 57 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-Lu2shbm7WXayLDmdkCg:-Lu2shbm7WXayLDmdkCh:b-g2hzm8) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/3d4f3629499f6a6aa9a260cc50384cd4bf95b84d/utils/docker/images/install-libpmemobj-cpp.sh#L57)):*
> ```Shell
> 	make -j$(nproc) install
> else
> 	make -j$(nproc) package
> ```

`make -j$(nproc) package` will return error if `$PACKAGE_TYPE` is different than `RPM` or `DEB`
___
*[utils/docker/images/install-pmdk.sh, line 51 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-Lu2sqmN-15Y-uO2ivw1:-Lu2sqmN-15Y-uO2ivw2:b-35zrao) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/3d4f3629499f6a6aa9a260cc50384cd4bf95b84d/utils/docker/images/install-pmdk.sh#L51)):*
> ```Shell
> 	make -j$(nproc) install prefix=/usr
> else
> 	make -j$(nproc) BUILD_PACKAGE_CHECK=n $PACKAGE_TYPE
> ```

`make -j$(nproc) BUILD_PACKAGE_CHECK=n $PACKAGE_TYPE` will return error if `$PACKAGE_TYPE` is different than `RPM` or `DEB`

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/install-libpmemobj-cpp.sh, line 57 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-Lu2shbm7WXayLDmdkCg:-Lu82A5J9EWBdEqNFlrN:bige1ak) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/3d4f3629499f6a6aa9a260cc50384cd4bf95b84d/utils/docker/images/install-libpmemobj-cpp.sh#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`make -j$(nproc) package` will return error if `$PACKAGE_TYPE` is different than `RPM` or `DEB`
</blockquote></details>

as in ruby, I wouldn't change it, error with nice description would be given by cmake
___
*[utils/docker/images/install-pmdk.sh, line 51 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-Lu2sqmN-15Y-uO2ivw1:-Lu82Aci52G_MP5hhnXN:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/3d4f3629499f6a6aa9a260cc50384cd4bf95b84d/utils/docker/images/install-pmdk.sh#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`make -j$(nproc) BUILD_PACKAGE_CHECK=n $PACKAGE_TYPE` will return error if `$PACKAGE_TYPE` is different than `RPM` or `DEB`
</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48#-:-Lu83LztB2zYsVE0KddK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/48)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
