### PR TITLE
support buffer arguments

### PR DESCRIPTION
**Pull request by how759**
Support both string arguments and Buffer arguments
Usage:
```
// use Buffer as argument
var buf = Buffer.from("key")
kv.get(buf);
```

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/18)

### CODE REVIEW

**Comment by ldorau** [comment]
@how759 please rebase

**Comment by ldorau** [comment]
@how759 please rebase

**Review by ldorau — COMMENTED** [review]
@how759 please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/18#-:-Lu31EXd1e45korQO-Py:b-vygou8)* status: 0 of 3 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/18)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by how759** [comment]
> @how759 please rebase
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/18#-:-Lu31EXd1e45korQO-Py:b-vygou8)_ status: 0 of 3 files reviewed, all discussions resolved

Hard to merge conflict due to original repo broken, I will make another PR

**Pull request closed without merging**
