### PR TITLE
Add doc comments

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41)

### CODE REVIEW

**Review by szyrom — COMMENTED** [review]
so far so good

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-:-LqLe1Yp8hqhXVlkO2Bn:ba37uh)* status: 3 of 4 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 77 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqM3FcO6yMIDv6lmzMy:-LqM3FcO6yMIDv6lmzMz:beoni8c) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/df6c391686c87cc615e04adb41823fcc99db6503/utils/docker/images/Dockerfile.ubuntu-19.04#L77)):*
> ```
> 
> # Install jsdoc for documentation
> npm install -g jsdoc
> ```

Why do you do that? Is it really necessary in the Docker file?

https://travis-ci.org/pmem/pmemkv-nodejs/builds/593554747#L499:
"Error response from daemon: Dockerfile parse error line 77: unknown instruction: NPM"

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 77 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqM9q2ZCibDdWHyFqDt:-LqM9q2_1_RfYw1987L2:b-8w19t2) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/df6c391686c87cc615e04adb41823fcc99db6503/utils/docker/images/Dockerfile.ubuntu-19.04#L77)):*
> ```
> 
> # Install jsdoc for documentation
> npm install -g jsdoc
> ```

RUN ....

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41)* status: 3 of 4 files reviewed, all discussions resolved

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[lib/database.js, line 98 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMD5vT01-6E5lgkyz1:-LqMD5vV8qDyDcH8W4vk:b3r7v0v) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L98)):*
> ```JavaScript
> 	 * Executes function for every record stored in db, whose keys are
> 	 *	greater than *key*. Callback is called only with key of each record.
> 	 *
> ```

mention Lexicographical order  ?
___
*[lib/database.js, line 112 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDKTA9710y8QtQXh4:-LqMDKTA9710y8QtQXh5:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L112)):*
> ```JavaScript
> 	 * Executes function for every record stored in db, whose keys are
> 	 *	less than the *key*. Callback is called only with key of each record.
> 	 *
> ```

.
___
*[lib/database.js, line 127 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDLlc66DS4GBbLcgs:-LqMDLlc66DS4GBbLcgt:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L127)):*
> ```JavaScript
> 	 *	greater than *key1* and less than *key2*. Callback is called
> 	 *	only with key of each record.
> 	 *
> ```

.
___
*[lib/database.js, line 204 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDaSr32FSFt9LJmNs:-LqMDaSr32FSFt9LJmNt:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L204)):*
> ```JavaScript
> 	 * Executes function for every record stored in db, whose keys are
> 	 *	greater than *key*.
> 	 *
> ```

.
___
*[lib/database.js, line 217 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDcATDtQV4OtGe7jp:-LqMDcATDtQV4OtGe7jq:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L217)):*
> ```JavaScript
> 	 * Executes function for every record stored in db, whose keys are
> 	 *	less than the *key*.
> 	 *
> ```

.
___
*[lib/database.js, line 230 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDdLV3ENjskXkp3en:-LqMDdLV3ENjskXkp3eo:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L230)):*
> ```JavaScript
> 	 * Executes function for every record stored in db, whose keys are
> 	 *	greater than *key1* and less than *key2*.
> 	 *
> ```

.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @karczex)

___
*[lib/database.js, line 98 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMD5vT01-6E5lgkyz1:-LqMHFm00rOzt5q9l17K:bb710yj) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L98)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

mention Lexicographical order  ?
</blockquote></details>

Nope
___
*[lib/database.js, line 112 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDKTA9710y8QtQXh4:-LqMHIkvCqwel94xVA1W:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L112)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[lib/database.js, line 127 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDLlc66DS4GBbLcgs:-LqMHK0B3Qbl4JlzJhP9:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L127)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[lib/database.js, line 204 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDaSr32FSFt9LJmNs:-LqMHLK024IdGLU3p3T2:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L204)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[lib/database.js, line 217 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDcATDtQV4OtGe7jp:-LqMHLwHC4iIQJInvLxU:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L217)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[lib/database.js, line 230 at r3](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqMDdLV3ENjskXkp3en:-LqMHMRp7cmFFXy5m1_f:b3kqx) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/ff2054761cf485a7ea1d9bd57ef76fd24dda2d46/lib/database.js#L230)):*
<details><summary><i>Previously, karczex wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 77 at r2](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41#-LqM9q2ZCibDdWHyFqDt:-LqMAiT5BTZrf3LeqOuL:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/df6c391686c87cc615e04adb41823fcc99db6503/utils/docker/images/Dockerfile.ubuntu-19.04#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

RUN ....
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/41)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex)

**Pull request merged**
