### PR TITLE
Replace PMEMKV_STATUS_FAILED with PMEMKV_STATUS_UNKNOWN_ERROR

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/34)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/34)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[lib/database.cc, line 232 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/34#-Lp2PEON8Z9U6zkM34fA:-Lp2PEON8Z9U6zkM34fB:b-cn0h0d) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/970b94dc6fe2f8bdc461e7062e743a0196238e29/lib/database.cc#L232)):*
> ```cpp
>     else if (status == pmem::kv::status::NOT_FOUND) {
>         return env.Undefined();
>     } else if (status == pmem::kv::status::UNKNOWN_ERROR) {
> ```

"else" should be enough, to throw exception on all errors

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/34)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[lib/database.cc, line 232 at r1](https://reviewable.io/reviews/pmem/pmemkv-nodejs/34#-Lp2PEON8Z9U6zkM34fA:-Lp2QhZSC534RTLrA_fl:b-896fix) ([raw file](https://github.com/pmem/pmemkv-nodejs/blob/970b94dc6fe2f8bdc461e7062e743a0196238e29/lib/database.cc#L232)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"else" should be enough, to throw exception on all errors
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/34#-:-Lp3fWjh2Jfxmhp2Jxnz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-nodejs/34#-:-Lp2Sr-KBn5ByvdTqVjn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
